#!/usr/bin/env bash

PID_FILE="/var/run/my_process.pid"

case "$1" in
    start)
        if [ -f "$PID_FILE" ]; then
            echo "manage_my_process is already running!"
        else
            ./manage_my_process &
            echo $! > "$PID_FILE"
            echo "manage_my_process started"
        fi
        ;;
    stop)
        if [ -f "$PID_FILE" ]; then
            PID=$(cat "$PID_FILE")
            kill $PID
            rm -f "$PID_FILE"
            echo "manage_my_process stopped"
        else
            echo "manage_my_process is not running!"
        fi
        ;;
    restart)
        if [ -f "$PID_FILE" ]; then
            PID=$(cat "$PID_FILE")
            kill $PID
            rm -f "$PID_FILE"
        fi
        ./manage_my_process &
        echo $! > "$PID_FILE"
        echo "manage_my_process restarted"
        ;;
    *)
        echo "Usage: manage_my_process {start|stop|restart}"
        exit 1
        ;;
esac

